pimcore:
    objects:
        class_definitions:
            data:
                map:
                    permissionHref: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinition\PermissionHref
                    permissionObjects: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinition\PermissionObjects
                    permissionResource: FrontendPermissionToolkitBundle\CoreExtensions\ClassDefinition\PermissionResource
